I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 50, in script
    music fadeout "5"
Exception: Sayer 'music' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 50, in script
    music fadeout "5"
  File "C:\Users\User\Downloads\renpy-7.1.3-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\User\Downloads\renpy-7.1.3-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'music' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
The Runaway 1.0
Thu Dec 06 23:27:55 2018
